# modules/report_generator.py

# -----------------------------------------------
# Report Generator Module
# Produces two outputs:
#   1. JSON report — machine-readable, importable
#   2. HTML report — human-readable, professional
#      styled like a real pentest deliverable
# Uses Jinja2 for HTML templating
# -----------------------------------------------

import json
import os
from datetime import datetime
from jinja2 import Template
from config import REPORT_OUTPUT_DIR


# ── HTML TEMPLATE ────────────────────────────────────────────────────────────
# Jinja2 template — {{ variables }} and {% for loops %} are filled at runtime
# This is a self-contained HTML file with embedded CSS

HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>AutoRecon Report — {{ target }}</title>
    <style>
        body        { font-family: 'Segoe UI', monospace; background: #0d1117; color: #c9d1d9; margin: 0; padding: 20px; }
        h1          { color: #58a6ff; border-bottom: 1px solid #30363d; padding-bottom: 10px; }
        h2          { color: #79c0ff; margin-top: 30px; }
        h3          { color: #d2a8ff; }
        .meta       { color: #8b949e; font-size: 0.9em; margin-bottom: 20px; }
        .section    { background: #161b22; border: 1px solid #30363d; border-radius: 6px; padding: 15px; margin: 15px 0; }
        .badge      { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 0.8em; font-weight: bold; margin-left: 8px; }
        .critical   { background: #b91c1c; color: white; }
        .high       { background: #c2410c; color: white; }
        .medium     { background: #a16207; color: white; }
        .low        { background: #15803d; color: white; }
        .port-card  { background: #0d1117; border: 1px solid #30363d; border-radius: 4px; padding: 10px; margin: 8px 0; }
        .cve-item   { border-left: 3px solid #388bfd; padding: 5px 10px; margin: 5px 0; background: #1c2128; }
        .cve-id     { color: #58a6ff; font-weight: bold; }
        a           { color: #58a6ff; }
        .subdomain  { color: #3fb950; font-family: monospace; }
        table       { width: 100%; border-collapse: collapse; }
        td, th      { padding: 8px 12px; border: 1px solid #30363d; text-align: left; }
        th          { background: #161b22; color: #8b949e; }
    </style>
</head>
<body>
    <h1>🔍 AutoRecon Security Report</h1>
    <div class="meta">
        <strong>Target:</strong> {{ target }} &nbsp;|&nbsp;
        <strong>Scan Date:</strong> {{ scan_date }} &nbsp;|&nbsp;
        <strong>Total Subdomains:</strong> {{ subdomains|length }} &nbsp;|&nbsp;
        <strong>Open Ports:</strong> {{ open_ports|length }}
    </div>

    <!-- SUBDOMAINS SECTION -->
    <h2>📡 Discovered Subdomains</h2>
    <div class="section">
    {% if subdomains %}
        <table>
            <tr><th>Subdomain</th><th>IP Addresses</th></tr>
            {% for sub in subdomains %}
            <tr>
                <td class="subdomain">{{ sub.subdomain }}</td>
                <td>{{ sub.ips | join(', ') }}</td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
        <p>No subdomains discovered.</p>
    {% endif %}
    </div>

    <!-- OPEN PORTS SECTION -->
    <h2>🔓 Open Ports & Services</h2>
    {% for port in open_ports %}
    <div class="port-card">
        <h3>Port {{ port.port }}/tcp — {{ port.service }}
            {% if port.cves %}
            <span class="badge high">{{ port.cves|length }} CVEs</span>
            {% endif %}
        </h3>
        
        {% if port.banner %}
        <p><strong>Banner:</strong> <code>{{ port.banner[:100] }}</code></p>
        {% endif %}
        
        {% if port.cves %}
        <p><strong>Known Vulnerabilities:</strong></p>
        {% for cve in port.cves %}
        <div class="cve-item">
            <span class="cve-id">{{ cve.id }}</span>
            <span class="badge 
                {% if cve.severity == 'CRITICAL' %}critical
                {% elif cve.severity == 'HIGH' %}high
                {% elif cve.severity == 'MEDIUM' %}medium
                {% else %}low{% endif %}">
                {{ cve.severity }} {{ cve.score }}
            </span>
            <p>{{ cve.description }}</p>
            <a href="{{ cve.url }}" target="_blank">View on NVD →</a>
        </div>
        {% endfor %}
        {% endif %}
    </div>
    {% endfor %}

    <div class="meta" style="margin-top:40px;">Generated by AutoRecon v1.0 | For authorized use only</div>
</body>
</html>
"""


def generate_report(target: str, subdomains: list, open_ports: list) -> dict:
    """
    Generate both HTML and JSON reports.
    
    Args:
        target:     The scanned domain/IP
        subdomains: List from subdomain_enum.py
        open_ports: List from port_scanner.py (with CVEs injected)
    
    Returns:
        Dict with paths to generated files
    """
    
    os.makedirs(REPORT_OUTPUT_DIR, exist_ok=True)   # Create reports/ folder if needed
    
    # Clean filename — replace dots with underscores
    safe_name = target.replace(".", "_").replace(":", "_")
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    
    scan_date = datetime.now().strftime("%B %d, %Y at %H:%M:%S")
    
    # ── JSON REPORT ──────────────────────────────────────────────────────────
    # Raw data dump — useful for importing into other tools or databases
    
    json_data = {
        "target":     target,
        "scan_date":  scan_date,
        "summary": {
            "total_subdomains": len(subdomains),
            "total_open_ports": len(open_ports),
            "total_cves":       sum(len(p.get("cves", [])) for p in open_ports)
        },
        "subdomains": subdomains,
        "open_ports": open_ports
    }
    
    json_path = os.path.join(REPORT_OUTPUT_DIR, f"{safe_name}_{timestamp}.json")
    
    with open(json_path, "w") as f:
        json.dump(json_data, f, indent=4)   # indent=4 = pretty-printed JSON
    
    print(f"\n[+] JSON report saved: {json_path}")
    
    # ── HTML REPORT ──────────────────────────────────────────────────────────
    # Jinja2 renders the template by substituting all {{ variables }}
    
    template = Template(HTML_TEMPLATE)
    html_content = template.render(
        target=target,
        scan_date=scan_date,
        subdomains=subdomains,
        open_ports=open_ports
    )
    
    html_path = os.path.join(REPORT_OUTPUT_DIR, f"{safe_name}_{timestamp}.html")
    
    with open(html_path, "w") as f:
        f.write(html_content)
    
    print(f"[+] HTML report saved: {html_path}")
    
    return {"json": json_path, "html": html_path}